#!/usr/bin/env python3
"""
production/generate_ctau_tables.py

Compute HNL proper decay length (cτ) vs mass for each flavor at U²=1.

Uses HNLCalc to compute the total decay width → lifetime → cτ.

Output: output/ctau/ctau_{Ue,Umu,Utau}.dat
Format: mN_GeV  ctau_meters_at_Usq1
"""

import sys
import numpy as np
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))
sys.path.insert(0, str(PROJECT_ROOT / "vendored" / "HNLCalc"))

from config_mass_grid import MASS_GRID

OUTPUT_DIR = PROJECT_ROOT / "output" / "ctau"


def compute_ctau_table(flavor, masses):
    """
    Compute cτ(m_N) at U²=1 for a given flavor.

    HNLCalc.get_br_and_ctau generates decay widths and BRs;
    we use gen_ctau to get the total width → cτ.

    Parameters
    ----------
    flavor : str
        "Ue", "Umu", or "Utau"
    masses : list of float
        HNL mass points in GeV.

    Returns
    -------
    ndarray, shape (N, 2)
        Columns: [m_N (GeV), ctau (meters)] at U²=1.
    """
    from HNLCalc import HNLCalc

    if flavor == "Ue":
        hnl = HNLCalc(ve=1, vmu=0, vtau=0)
    elif flavor == "Umu":
        hnl = HNLCalc(ve=0, vmu=1, vtau=0)
    elif flavor == "Utau":
        hnl = HNLCalc(ve=0, vmu=0, vtau=1)
    else:
        raise ValueError(f"Unknown flavor: {flavor}")

    mpts = np.array(masses)
    coupling = 1.0

    # gen_ctau computes total width and stores ctau in hnl.ctau
    hnl.gen_ctau(mpts, coupling)

    # hnl.ctau contains ctau in meters for each mass point
    ctau_arr = np.array(hnl.ctau)

    return np.column_stack([mpts, ctau_arr])


def compute_br_vis_table(flavor, masses):
    """
    Compute visible branching ratio BR_vis(m_N) = fraction of decays
    producing >= 2 charged tracks.

    Subtracts modes with no charged particles in the final state:
      - N→ννν (truly invisible)
      - N→νπ⁰, N→νη, N→νη' (neutral pseudoscalar — no charged tracks)

    NC vector modes (N→νρ⁰→νπ⁺π⁻, etc.) DO produce charged tracks
    and are counted as visible.

    Parameters
    ----------
    flavor : str
        "Ue", "Umu", or "Utau"
    masses : list of float
        HNL mass points in GeV.

    Returns
    -------
    ndarray, shape (N, 2)
        Columns: [m_N (GeV), BR_vis (dimensionless)].
    """
    from HNLCalc import HNLCalc

    if flavor == "Ue":
        hnl = HNLCalc(ve=1, vmu=0, vtau=0)
    elif flavor == "Umu":
        hnl = HNLCalc(ve=0, vmu=1, vtau=0)
    elif flavor == "Utau":
        hnl = HNLCalc(ve=0, vmu=0, vtau=1)
    else:
        raise ValueError(f"Unknown flavor: {flavor}")

    mpts = np.array(masses)
    hnl.gen_ctau(mpts, coupling=1)
    hnl.gen_brs()

    # Modes producing zero charged tracks
    no_track_modes = [
        ('nu', 'nu', 'nu'),   # invisible
        ('nu', 'pi0'),         # neutral pseudoscalar
        ('nu', 'eta'),         # neutral pseudoscalar
        ('nu', 'etap'),        # neutral pseudoscalar
    ]
    n = len(mpts)
    br_no_tracks = np.zeros(n)
    for mode in no_track_modes:
        if mode in hnl.model_brs:
            br_no_tracks += np.array(hnl.model_brs[mode])
    br_vis = 1.0 - br_no_tracks

    return np.column_stack([mpts, br_vis])


def main():
    import argparse

    parser = argparse.ArgumentParser(description="Generate HNL cτ tables")
    parser.add_argument("--flavor", choices=["Ue", "Umu", "Utau"], nargs="+",
                        default=["Ue", "Umu", "Utau"])
    parser.add_argument("--masses", type=float, nargs="+", default=None)
    parser.add_argument("--no-br-vis", action="store_true",
                        help="Skip visible branching ratio tables (generated by default)")
    args = parser.parse_args()

    masses = args.masses if args.masses else MASS_GRID
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    for flavor in args.flavor:
        print(f"Computing cτ for {flavor} ({len(masses)} mass points)...")
        table = compute_ctau_table(flavor, masses)
        out_path = OUTPUT_DIR / f"ctau_{flavor}.dat"
        np.savetxt(out_path, table, header="mN_GeV  ctau_meters_at_Usq1",
                   fmt=["%.4f", "%.6e"])
        print(f"  → {out_path}")
        # Print a few values for sanity check
        for i in [0, len(masses)//4, len(masses)//2, -1]:
            print(f"    m_N = {table[i,0]:.2f} GeV → cτ = {table[i,1]:.3e} m")

        if not args.no_br_vis:
            print(f"Computing BR_vis for {flavor}...")
            br_table = compute_br_vis_table(flavor, masses)
            br_path = OUTPUT_DIR / f"br_vis_{flavor}.dat"
            np.savetxt(br_path, br_table, header="mN_GeV  br_vis",
                       fmt=["%.4f", "%.6e"])
            print(f"  → {br_path}")
            for i in [0, len(masses)//4, len(masses)//2, -1]:
                print(f"    m_N = {br_table[i,0]:.2f} GeV → BR_vis = {br_table[i,1]:.4f}")

    print("Done.")


if __name__ == "__main__":
    main()
