#!/usr/bin/env python3
"""
GRENDEL millicharged-particle reach in the (mass, charge) plane.

Signal model
------------
    N(m, Q) = L * sigma(m) * Q^2 * pAny(m) * eps(Q)

    sigma(m)  Drell-Yan gamma*/Z pair production at Q = e, 14 TeV, from
              out/results_gmZ.json.  Generated by mcp_dy.cc (Pythia 8.315
              semi-internal process) and reduced by analyze.py.  Scales
              as Q^2.
    pAny(m)   per-EVENT probability that at least one of the two MCPs
              crosses the GRENDEL tracker, from out/per_event_gmZ.json
              (per_event.py).
              NOTE: this is the per-event quantity (pAny = Nacc - pBoth),
              NOT the per-particle I_all / perPart.  Using the per-particle
              number would undercount by ~2.
    eps(Q)    [ P(NMIN <= N <= NMAX | lambda = NPE * Q^2) ]^4
              Poisson photon count in each of the four scintillator planes.
              NMAX is set by the muon-rejection requirement (see below);
              set REJECT_MUONS = False to drop the upper cut and get the
              open (one-sided) curves instead.

Muon rejection
--------------
A muon is a Q = e particle, so its mean photon count per plane is NPE.
Requiring [P(N <= NMAX | NPE)]^4 <= 1/N_MU fixes NMAX.  This also bounds
the signal from above: a Q -> e particle is indistinguishable from a muon
by ionisation, so the exclusion contour closes below Q = e.

    N_MU = 2e9  ->  NMAX = 74 (NPE = 100),  NMAX = 163 (NPE = 200)

Geometry
--------
The acceptance in the JSON was computed against external/A_eta.npy, the
azimuthal fraction of the GRENDEL tracker surface vs pseudorapidity,
obtained by ray-casting the fiducial mesh from the CMS IP.  Isotropic
closure: sum A(eta) * 0.5 sech^2(eta) * d_eta = 0.02384.  This script does
not read it -- analyze.py and per_event.py already folded it in -- but it
is checked against A_ISO below so the two cannot drift apart.

Usage
-----
    python make_mcp_plot.py                # closed contours (default)
    python make_mcp_plot.py --open         # one-sided Qmin curves
    python make_mcp_plot.py --outdir figs  # default: out/
"""

import argparse
import json
import os

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from matplotlib.patches import Patch
from matplotlib.ticker import FixedLocator, FixedFormatter, NullFormatter
from scipy.optimize import brentq
from scipy.stats import poisson

# ----------------------------------------------------------------------
# Configuration
# ----------------------------------------------------------------------
LUMI_FB = 3000.0        # 3 ab^-1
NSIG = 3.0              # events required for sensitivity
N_MU = 2.0e9            # muons to reject
NLAYER = 4              # scintillator planes traversed
A_ISO = None            # taken from the results file (a_iso), see check_a_iso

# (NMIN, NPE at Q = e, colour, linestyle, filled)
CONFIGS = [
    (10, 100.0, "C3", "-",             True),
    (10, 200.0, "C0", "-",             True),
    (5,  100.0, "C3", (0, (1.6, 1.6)), False),
    (5,  200.0, "C0", (0, (1.6, 1.6)), False),
]

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "out")          # generator output, written by analyze.py
EXT = os.path.join(HERE, "external")     # digitised curves from other experiments


# ----------------------------------------------------------------------
# Muon-rejection threshold
# ----------------------------------------------------------------------
def nmax_for_rejection(npe, n_mu=N_MU, nlayer=NLAYER):
    """Largest per-plane photon count whose muon survival probability,
    raised to nlayer, stays below 1 / n_mu."""
    per_layer = (1.0 / n_mu) ** (1.0 / nlayer)
    k = 0
    while poisson.cdf(k, npe) <= per_layer:
        k += 1
    return k - 1


# ----------------------------------------------------------------------
# Signal model
# ----------------------------------------------------------------------
def load_signal():
    with open(os.path.join(OUT, "results_gmZ.json")) as fh:
        res = {r["m"]: r for r in json.load(fh)}
    with open(os.path.join(OUT, "per_event_gmZ.json")) as fh:
        per = {r["m"]: r for r in json.load(fh)}

    check_a_iso(res)
    masses = np.array(sorted(res), dtype=float)
    # sanity: the two files must describe the same sample
    dmax = max(abs(per[m]["perPart"] - res[m]["I_all"]) for m in masses)
    assert dmax < 1e-12, "results/per_event mismatch: %.2e" % dmax

    sigma = np.array([res[m]["sigma_fb"] for m in masses])
    p_any = np.array([per[m]["pAny"] for m in masses])
    return masses, sigma, p_any


def check_a_iso(res, tol=1e-6):
    """The acceptances in the JSON were folded through one particular A(eta);
    verify that external/A_eta.npy is still that array, so the plot cannot be
    built from a geometry the acceptances did not come from."""
    rec = next(iter(res.values()))
    if "a_iso" not in rec:
        return                      # produced before analyze.py recorded it
    path = os.path.join(EXT, rec.get("a_eta", "A_eta.npy"))
    if not os.path.exists(path):
        raise SystemExit("A(eta) used for the acceptances is missing: %s" % path)
    eta, a = np.load(path)
    iso = float((a * 0.5 / np.cosh(eta) ** 2 * (eta[1] - eta[0])).sum())
    if abs(iso - rec["a_iso"]) > tol * rec["a_iso"]:
        raise SystemExit(
            "%s has closure %.6f but the acceptances were built with %.6f -- "
            "rerun analyze.py and per_event.py" % (path, iso, rec["a_iso"]))
    return iso


def make_interp(masses, values):
    """Log-log linear interpolation in mass."""
    lm, lv = np.log(masses), np.log(values)
    return lambda m: np.exp(np.interp(np.log(m), lm, lv))


def efficiency(Q, nmin, npe, nmax):
    lam = npe * np.asarray(Q) ** 2
    lo = poisson.cdf(nmin - 1, lam)
    hi = 1.0 if nmax is None else poisson.cdf(nmax, lam)
    return (hi - lo) ** NLAYER


def n_events(Q, m, nmin, npe, nmax, sig_of, acc_of):
    return LUMI_FB * sig_of(m) * np.asarray(Q) ** 2 * acc_of(m) \
        * efficiency(Q, nmin, npe, nmax)


def solve_contour(masses, nmin, npe, nmax, sig_of, acc_of):
    """Return (Q_low, Q_high) per mass; Q_high is NaN when nmax is None."""
    grid = np.logspace(-2, 0.05, 600)
    lo, hi = [], []
    for m in masses:
        f = lambda q: n_events(q, m, nmin, npe, nmax, sig_of, acc_of) - NSIG
        sign_changes = np.where(np.diff(np.sign(f(grid))))[0]
        if len(sign_changes) == 0:
            lo.append(np.nan)
            hi.append(np.nan)
            continue
        i = sign_changes[0]
        lo.append(brentq(f, grid[i], grid[i + 1]))
        if nmax is not None and len(sign_changes) >= 2:
            j = sign_changes[-1]
            hi.append(brentq(f, grid[j], grid[j + 1]))
        else:
            hi.append(np.nan)
    return np.array(lo), np.array(hi)


# ----------------------------------------------------------------------
# External curves
# ----------------------------------------------------------------------
def load_external():
    ld = lambda n: np.loadtxt(os.path.join(EXT, n), delimiter=",")
    cms = ld("CMS.csv")
    return {
        "milliqan": ld("milliQanRun3Fix.csv"),   # lower boundary, mass-dependent
        "formosa": ld("FORMOSA_nominal2ab.csv"),  # projection, 2 ab^-1
        "collider": ld("Collider.csv"),           # LEP: excluded ABOVE, m < mZ/2
        "cms": np.vstack([cms, cms[:1]]),         # closed contour
    }


def draw_external(ax, ext, grey="0.50", edge="0.28"):
    col, mq, cms, fm = ext["collider"], ext["milliqan"], ext["cms"], ext["formosa"]

    # LEP: excluded above the curve, terminating at mZ/2
    poly = np.vstack([col, [[col[-1, 0], 1.0], [col[0, 0], 1.0]]])
    ax.fill(poly[:, 0], poly[:, 1], color=grey, alpha=.5, lw=0, zorder=1)
    ax.plot(col[:, 0], col[:, 1], color=edge, lw=1.2, zorder=3)

    # milliQan: between its own lower boundary and the LEP bound above it
    upper = np.interp(mq[:, 0], col[:, 0], col[:, 1])
    ax.fill_between(mq[:, 0], mq[:, 1], np.maximum(upper, mq[:, 1]),
                    color=grey, alpha=.5, lw=0, zorder=1)
    ax.plot(mq[:, 0], mq[:, 1], color=edge, lw=1.2, zorder=3)

    ax.fill(cms[:, 0], cms[:, 1], color=grey, alpha=.5, lw=0, zorder=1)
    ax.plot(cms[:, 0], cms[:, 1], color=edge, lw=1.2, zorder=3)

    ax.plot(fm[:, 0], fm[:, 1], color="C2", lw=2.2, ls=(0, (7, 2.5)), zorder=4)

    # in-plot labels
    ax.text(22, 0.62, "colliders (LEP)", ha="center", fontsize=9, color="0.10")
    ax.text(140, 0.72, "CMS FCP", ha="center", fontsize=9, color="0.10")
    mlab = 12.5
    a = np.interp(mlab, mq[:, 0], mq[:, 1])
    b = np.interp(mlab, col[:, 0], col[:, 1])
    ax.text(mlab, np.sqrt(a * b), "milliQan Run 3", ha="center", va="center",
            fontsize=6.5, color="0.05", zorder=6)


# ----------------------------------------------------------------------
# Main
# ----------------------------------------------------------------------
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--open", action="store_true",
                    help="drop the muon upper cut; draw one-sided Qmin curves")
    ap.add_argument("--outdir", default=OUT)
    args = ap.parse_args()
    os.makedirs(args.outdir, exist_ok=True)

    masses, sigma, p_any = load_signal()
    sig_of = make_interp(masses, sigma)
    acc_of = make_interp(masses, p_any)
    ext = load_external()

    grid = np.unique(np.concatenate([
        np.logspace(1, 3, 150),      # 10 GeV - 1 TeV
        np.linspace(34, 52, 40),     # fine near the Z threshold
    ]))

    fig, ax = plt.subplots(figsize=(8.0, 6.2))
    draw_external(ax, ext)

    handles = []
    for nmin, npe, colour, ls, filled in CONFIGS:
        nmax = None if args.open else nmax_for_rejection(npe)
        lo, hi = solve_contour(grid, nmin, npe, nmax, sig_of, acc_of)
        good = ~np.isnan(lo)

        if args.open:
            ax.plot(grid[good], lo[good], color=colour, ls=ls,
                    lw=2.4 if filled else 2.0, zorder=5)
            label = r"$N_{\rm PE}\geq %d$, %d PE at $Q=e$" % (nmin, npe)
            out = np.column_stack([grid, lo])
            header = "mass_GeV,Qmin"
        else:
            ok = good & ~np.isnan(hi)
            xs = np.concatenate([grid[ok], grid[ok][::-1]])
            ys = np.concatenate([lo[ok], hi[ok][::-1]])
            xs, ys = np.append(xs, xs[0]), np.append(ys, ys[0])
            if filled:
                ax.fill(xs, ys, color=colour, alpha=.15, lw=0, zorder=4)
            ax.plot(xs, ys, color=colour, ls=ls,
                    lw=2.4 if filled else 2.0, zorder=5)
            label = r"$%d\leq N_{\rm PE}\leq %d$, %d PE at $Q=e$" % (nmin, nmax, npe)
            out = np.column_stack([grid, lo, hi])
            header = "mass_GeV,Q_low,Q_high"

        handles.append(Line2D([], [], color=colour, ls=ls,
                              lw=2.4 if filled else 2.0, label=label))
        # The open and closed runs hold different columns, so they must not
        # share a filename -- otherwise whichever ran last silently wins.
        mode = "open" if args.open else "closed"
        np.savetxt(os.path.join(args.outdir, "grendel_mcp_N%d_%dPE_%s.csv"
                                % (nmin, npe, mode)),
                   out, delimiter=",", fmt="%.6g", header=header)

    ax.axhline(1 / 3, color="k", lw=.9, ls="-.", zorder=2)
    ax.text(760, 0.348, r"$Q=e/3$", fontsize=8.5)

    legend = [
        Patch(facecolor="0.50", alpha=.5, edgecolor="0.28",
              label="Existing exclusions (LEP, milliQan Run 3, CMS FCP)"),
        Line2D([], [], color="C2", ls=(0, (7, 2.5)), lw=2.2,
               label=r"FORMOSA projection, 2 ab$^{-1}$ (nominal)"),
    ] + handles
    ax.legend(handles=legend, loc="upper center", bbox_to_anchor=(0.5, -0.11),
              ncol=2, fontsize=8.2, framealpha=1.0,
              title=r"GRENDEL, 3 ab$^{-1}$", title_fontsize=8.5)

    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.set_xlim(10, 1000)
    ax.set_ylim(0.09, 1.05)
    ticks = [0.09, 0.1, 0.15, 0.2, 0.3, 0.4, 0.5, 0.7, 1.0]
    ax.yaxis.set_major_locator(FixedLocator(ticks))
    ax.yaxis.set_major_formatter(FixedFormatter([str(t) for t in ticks]))
    ax.yaxis.set_minor_formatter(NullFormatter())
    ax.set_xlabel("MCP mass (GeV)")
    ax.set_ylabel(r"charge $Q/e$")
    title = r"GRENDEL MCP reach: 3 ab$^{-1}$, $N_{\rm sig}\geq3$"
    if not args.open:
        title += r", $2\times10^{9}$ muon rejection"
    else:
        title += ", background-free"
    ax.set_title(title)
    ax.grid(alpha=.3, which="both")

    name = "grendel_mcp_open.png" if args.open else "grendel_mcp_closed.png"
    path = os.path.join(args.outdir, name)
    fig.savefig(path, dpi=170, bbox_inches="tight")
    print("wrote", path)
    if not args.open:
        for _, npe, _, _, _ in CONFIGS[:2]:
            print("  NMAX(%d PE) = %d" % (npe, nmax_for_rejection(npe)))


if __name__ == "__main__":
    main()
